# Generated by Django 3.0.8 on 2020-11-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='hostel',
            field=models.CharField(default='B1', max_length=3),
            preserve_default=False,
        ),
    ]
