# Generated by Django 3.0.8 on 2020-11-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_webapp', '0003_auto_20201121_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='avatar',
        ),
    ]
