# Generated by Django 3.0.8 on 2020-11-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_webapp', '0006_remove_complaint_complaint_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='author',
            new_name='student',
        ),
    ]
